ShopOnline/Controllers/ProductionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Models;
using System.IO;


namespace ShopOnline.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductionController : Controller
    {
        private QLShopOnlineEntities db = new QLShopOnlineEntities();

        // GET: /Production/
        public ViewResult Index(string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.DescriptionlSortParm = sortOrder == "Description" ? "description_desc" : "Description";
            ViewBag.StockSortParm = sortOrder == "Stock" ? "stock_desc" : "Stock";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            ViewBag.CategorySortParm = sortOrder == "Category" ? "category_desc" : "Category";
           
            var productions = from s in db.Products
                              select s;

            switch (sortOrder)
            {
                case "name_desc":
                    productions = productions.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    productions = productions.OrderBy(s => s.TimeUpdate);
                    break;
                case "date_desc":
                    productions = productions.OrderByDescending(s => s.TimeUpdate);
                    break;
                case "Description":
                    productions = productions.OrderBy(s => s.Description);
                    break;
                case "description_desc":
                    productions = productions.OrderByDescending(s => s.Description);
                    break;
                case "Stock":
                    productions = productions.OrderBy(s => s.Stock);
                    break;
                case "stock_desc":
                    productions = productions.OrderByDescending(s => s.Stock);
                    break;
                case "Price":
                    productions = productions.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    productions = productions.OrderByDescending(s => s.Price);
                    break;
                case "Category":
                    productions = productions.OrderBy(s => s.Category.Name);
                    break;
                case "category_desc":
                    productions = productions.OrderByDescending(s => s.Category.Name);
                    break;
                default:
                    productions = productions.OrderBy(s => s.Name);
                    break;
            }

            return View(productions.ToList());

        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            var images = from i in db.ProductImages
                         where i.ProductID == id
                         select i;
            var sizes = from s in db.Sizes
                        where s.ProductID == id
                        select s;
            Session["lm"] = images;
            Session["ls"] = sizes;
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: /Production/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: /Production/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,CategoryID,Description,Stock,Price,TimeUpdate")] Product product, string size1, string size2, string size3, string size4, string size5, HttpPostedFileBase file, HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3)
        {
            //Thêm dữ liệu ảnh
            if (ModelState.IsValid)
            {
                List<string> ls = new List<string>();
                List<string> limg = new List<string>();
                CreateListSize(ls, size1);
                CreateListSize(ls, size2);
                CreateListSize(ls, size3);
                CreateListSize(ls, size4);
                CreateListSize(ls, size5);

                //Mycode 
                foreach (string s in ls)
                {
                    Size st = new Size();
                    st.ID = db.Sizes.ToList()[db.Sizes.ToList().Count - 1].ID + 1;
                    st.ProductID = product.ID;
                    st.Value = s;
                    db.Sizes.Add(st);
                }

                //Create image
                CreateImage(product, file, "1");
                CreateImage(product, file1, "2");
                CreateImage(product, file2, "3");
                CreateImage(product, file3, "4");
                product.NumView = 0;
                product.TimeUpdate = DateTime.Now;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        void CreateImage([Bind(Include = "ID,Name,CategoryID,Description,Stock,Price,TimeUpdate")] Product product, HttpPostedFileBase file, string num)
        {
            if (file != null && file.ContentLength > 0)
            {
                System.Drawing.Image image = System.Drawing.Image.FromStream(file.InputStream);
                String rootPath = Server.MapPath("~/Content/ShopOnline/images/");
                string sn = (db.Products.ToList()[db.Products.ToList().Count - 1].ID + 1).ToString();
                string s = "P" + sn + "T" + num;
                image.Save(@rootPath + s + ".jpg");
                ProductImage pimg = new ProductImage();
                pimg.ID = db.ProductImages.ToList()[db.ProductImages.ToList().Count - 1].ID + 1;
                pimg.ProductID = product.ID;
                pimg.URL = "~/Content/ShopOnline/images/" + s + ".jpg";
                pimg.Type = int.Parse(num);
                db.ProductImages.Add(pimg);
            }
        }

        void CreateListSize(List<string> l, string s)
        {
            if (s != null)
                l.Add(s);
        }




        // GET: /Production/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            var images = from i in db.ProductImages
                         where i.ProductID == product.ID
                         select i;
            var sizes = from i in db.Sizes
                        where i.ProductID == id
                        select i;
            Session["ls"] = sizes;
            Session["lm"] = images;

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // POST: /Production/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,CategoryID,Description,Stock,Price,TimeUpdate")] Product product, string size1, string size2, string size3, string size4, string size5, HttpPostedFileBase file, HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3)
        {
            if (ModelState.IsValid)
            {
                product.TimeUpdate = DateTime.Now;
                db.Entry(product).State = EntityState.Modified;
                List<string> ls = new List<string>();
                CreateListSize(ls, size1);
                CreateListSize(ls, size2);
                CreateListSize(ls, size3);
                CreateListSize(ls, size4);
                CreateListSize(ls, size5);
                var sizes = from s in db.Sizes
                            where s.ProductID == product.ID
                            select s;


                DeleteImage(file, 1, product);
                DeleteImage(file1, 2, product);
                DeleteImage(file2, 3, product);
                DeleteImage(file3, 4, product);

                //Delete
                foreach (Size s in sizes)
                {
                    db.Sizes.Remove(s);
                }

                //Add size
                foreach (string s in ls)
                {
                    Size st = new Size();
                    st.ID = db.Sizes.ToList()[db.Sizes.ToList().Count - 1].ID + 1;
                    st.ProductID = product.ID;
                    st.Value = s;
                    db.Sizes.Add(st);
                }

                //Add image
                if (file != null)
                    CreateImage(product, file, "1");
                if (file1 != null)
                    CreateImage(product, file1, "2");
                if (file2 != null)
                    CreateImage(product, file2, "3");
                if (file3 != null)

ShopOnline/Views/Production/Create.cshtml
@model ShopOnline.Models.Product

@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script language="JavaScript" type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    function readURL1(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah1')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    function readURL2(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah2')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    function readURL3(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#blah3')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

</script>
    
@using (Html.BeginForm("Create", "Production", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions">
        @Html.ValidationSummary(true)

        <div class="form-group">
            <div class="control-label col-md-2">
                <label>Tên sản phẩm</label>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <label>Chọn loại sản phẩm</label>
            </div>
            <div class="col-md-10">
                @Html.DropDownList("CategoryID")
                @Html.ValidationMessageFor(model => model.CategoryID)
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <label>Mô tả</label>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <label>Số lượng</label>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock)
                @Html.ValidationMessageFor(model => model.Stock)
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <label>Giá thành</label>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">

            <div class="control-label col-md-2">    
                <label>Kích thước</label>
            </div>
            <div class="control-label col-md-10">
                <input type="checkbox" name="size1" value="XS">XS
               
                <input type="checkbox" name="size2" value="S">S
               
                <input type="checkbox" name="size3" value="M">M
               
                <input type="checkbox" name="size4" value="L">L
              
                <input type="checkbox" name="size5" value="XL">XL
              
            </div>
           
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <label>Hình ảnh</label>
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file" id="file" onchange="readURL(this);" />
                <input type="image" id="blah" name="imagepost1" src="#" alt="your image" />
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file1" id="file" onchange="readURL1(this);" />
                <input type="image" id="blah1" name="imagepost2" src="#" alt="your image" />
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file2" id="file" onchange="readURL2(this);" />
                <input type="image" id="blah2" name="imagepost3" src="#" alt="your image" />
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file3" id="file" onchange="readURL3(this);" />
                <input type="image" id="blah3" name="imagepost4" src="#" alt="your image" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

ShopOnline/Views/Production/Delete.cshtml
@model ShopOnline.Models.Product

@{
    ViewBag.Title = "Xóa sản phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>Bạn muốn xóa sản phẩm này?</h3>
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }
</div>

ShopOnline/Views/Production/Details.cshtml
@model ShopOnline.Models.Product

@{
    ViewBag.Title = "Chi tiết sản phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var listImages = Session["lm"] as IEnumerable<ShopOnline.Models.ProductImage>;
    var Sizes = Session["ls"] as IEnumerable<ShopOnline.Models.Size>;
}

<div>
    <div class="row">
        <div class="col-sm-4" style="padding-top:5%">
            <dl class="dl-horizontal">
                <dt>
                    Tên sản phẩm
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    Mô tả
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                   Số lượng
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Stock)
                </dd>

                <dt>
                    Giá thành
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>

                <dt>
                   Thời gian cập nhật
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TimeUpdate)
                </dd>

                <dt>
                    Thể loại
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Category.Name)
                </dd>
                <dt>
                    Kích cỡ
                </dt>
                <dd>
                    @foreach (var s in @Sizes)
                    {
                        @s.Value
                    }
                </dd>
                <dt>
                    Hình ảnh
                </dt>
                <dd>
                    @foreach (var img in @listImages)
                    {
                        <img src="@Url.Content(@img.URL)" alt="" height="200" width="200" />

                    }
                </dd>
            </dl>
        </div>
    </div>
    <p>
        @Html.ActionLink("Sửa", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Trở lại", "Index")
    </p>
</div>

ShopOnline/Views/Production/Edit.cshtml
@model ShopOnline.Models.Product

@{
    ViewBag.Title = "Sửa sản phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var listImages = Session["lm"] as IEnumerable<ShopOnline.Models.ProductImage>;
    var Sizes = Session["ls"] as IEnumerable<ShopOnline.Models.Size>;
    string s1, s2, s3, s4, s5;
    string i1, i2, i3, i4;
    s1 = s2 = s3 = s4 = s5 = null;
    i1 = i2 = i3 = i4 = "#";
    foreach(var s in @Sizes)
    {
        string []temp = s.Value.Split(' ');
        if (temp[0] == "XS")
        { 
            s1 = "true";
        }
        if (temp[0] == "S")
        {
            s2 = "true";
        }
        if (temp[0] == "M")
        {
            s3 = "true";
        }
        if (temp[0] == "L")
        {
            s4 = "true";
        }
        if (temp[0] == "XL")
        {
            s5 = "true";
        }
    }
    foreach(var img in @listImages)
    {   
        if(img.Type==1)
        {
            i1 = img.URL;
        }
        else if (img.Type == 2)
        {
            i2 = img.URL;
        }
        else if (img.Type == 3)
        {
            i3 = img.URL;
        }
        else if (img.Type == 4)
        {
            i4 = img.URL;
        }
    }
}


<script language="JavaScript" type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    function readURL1(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah1')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    function readURL2(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah2')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    function readURL3(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah3')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

@using (Html.BeginForm("Edit", "Production", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name,"Tên sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "Thể loại", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description,"Mô tả", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock,"Số lượng", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock)
                @Html.ValidationMessageFor(model => model.Stock)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price,"Giá thành", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <label>Kích thước</label>
            </div>
            <div class="control-label col-md-10">
                <input type="checkbox" name="size1" value="XS" checked="@s1">XS<br>
                <input type="checkbox" name="size2" value="S" checked="@s2">S<br>
                <input type="checkbox" name="size3" value="M" checked="@s3">M<br>
                <input type="checkbox" name="size4" value="L" checked="@s4">L<br>
                <input type="checkbox" name="size5" value="XL" checked="@s5">XL<br>
            </div>
          
        </div>
        <div class="form-group">
            <div class="control-label col-md-2">  
                <label>Hình ảnh</label>
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file" id="file" onchange="readURL(this);" />
                <input type="image" id="blah" name="imagepost1" src="@Url.Content(@i1)"  alt="your image" width=100 height=100 />
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file1" id="file" onchange="readURL1(this);" />
                <input type="image" id="blah1" name="imagepost2" src="@Url.Content(@i2)" alt="your image" width=100 height=100 />
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file2" id="file" onchange="readURL2(this);" />
                <input type="image" id="blah2" name="imagepost3" src="@Url.Content(@i3)" alt="your image" width=100 height=100 />
            </div>
            <div class="control-label col-md-10">
                <input type='file' name="file3" id="file" onchange="readURL3(this);" />
                <input type="image" id="blah3" name="imagepost4" src="@Url.Content(@i4)" alt="your image" width=100 height=100 />
            </div>
            
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>




    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

ShopOnline/Views/Production/Index.cshtml
@model IEnumerable<ShopOnline.Models.Product>
@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white user"></i><span class="break"></span>Bảng sản phẩm</h2>
            <div class="box-icon">
                @Html.ActionLink("Thêm sản phẩm", "Create")
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>
                            Hình ảnh
                        </th>
                        <th>
                            @Html.ActionLink("Tên sản phẩm", "Index", new { sortOrder = ViewBag.NameSortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Mô tả", "Index", new { sortOrder = ViewBag.DescriptionlSortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Số lượng", "Index", new { sortOrder = ViewBag.StockSortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Giá", "Index", new { sortOrder = ViewBag.PriceSortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Ngày tải lên", "Index", new { sortOrder = ViewBag.DateSortParm})
                        </th>
                        <th>
                            @Html.ActionLink("Loại", "Index", new { sortOrder = ViewBag.CategorySortParm})
                        </th>
                        <th>
                            Các kích cỡ
                        </th>
                        <th>
                            Hành động
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        string pathImage = "";
                        if (item.ProductImages.Count() > 0)
                        {
                            var imageProduct = item.ProductImages.FirstOrDefault(i => i.Type == 1);
                            pathImage = imageProduct.URL;
                        }
                        <tr>
                            <td><img src="@Url.Content(@pathImage)" alt="" style="max-height:100px; max-width:100px" /></td>
                            <td class="center">@item.Name</td>
                            <td class="center">@item.Description</td>
                            <td class="center">@item.Stock</td>
                            <td class="center">@item.Price</td>
                            <td class="center">@item.TimeUpdate</td>
                            <td class="center">@item.Category.Name</td>
                            <td class="center">
                                @foreach (var s in @item.Sizes)
                                {
                                    <span class="label label-success">@s.Value</span>
                                }   
                            </td>
                            <td class="center">
                                <a class="btn btn-success" href="/Production/Details?id=@item.ID">
                                    <i class="halflings-icon white zoom-in"></i>
                                </a>
                                <a class="btn btn-info" href="/Production/Edit?id=@item.ID">
                                    <i class="halflings-icon white edit"></i>
                                </a>

                                <a class="btn btn-danger" href="/Production/Delete?id=@item.ID">
                                    <i class="halflings-icon white trash"></i>
                                </a>

                            </td>
                            
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div><!--/span-->

</div><!--/row-->